CREATE DATABASE QuanLyQuanCafe;

CREATE TABLE NhanVien (
    MaNV INT IDENTITY PRIMARY KEY,
    TenNV NVARCHAR(100),
    SDT NVARCHAR(20),
    DiaChi NVARCHAR(200),
    GioiTinh NVARCHAR(10),
    NgaySinh DATE,
    VaiTro NVARCHAR(50),
    Luong DECIMAL(18,2),
    TaiKhoan NVARCHAR(50),
    MatKhau NVARCHAR(50)
);